image:
  file: .gitpod.Dockerfile
  
  
tasks:
  - init: pip install -q tensorflow                                                &&
          pip install tensorflowjs                                                 &&
          pip install netron                                                       &&
          pip install -q tensorflow-quantum                                        &&
          node set01.py                                                            &&
          echo "upload your model.json and model.weights.bin files here then run ./a01-convert-tfjs-arduino.sh"                                                                                                                          

              
