image:
  file: .gitpod.Dockerfile
  
ports:
  - port: 6080
    onOpen: ignore 

  
tasks:
  - init:    pip3 install --upgrade pip                                             &&
             pip3 install tensorflow                                                &&
             pip3 install tensorflowjs                                              &&
             pip3 install netron                                                    &&
             pip3 install tensorflow-quantum                                        &&
             pip3 install matplotlib                                                &&
             cd pennylaneai                                                         &&
             cd qml-demos                                                           &&
             pip3 install -r requirements.txt                                       &&
             cd alldata                                                             &&
             wget https://download.pytorch.org/tutorial/hymenoptera_data.zip        &&
             unzip  hymenoptera_data.zip                                            &&
             rm  hymenoptera_data.zip                                               &&
             cd ..                                                                  &&
             chmod a+x a01-show-errors.sh                                           &&
             python3 tutorial_quantum_chemistry.py
             
             
             
