image:
  file: .gitpod.Dockerfile
  
ports:
  - port: 6080
    onOpen: ignore 
  
tasks:
  - init: pip3 install --upgrade pip                                             &&
          pip3 install tensorflow                                                &&
          pip3 install tensorflowjs                                              &&
          pip3 install netron                                                    &&
          pip3 install tensorflow-quantum                                        &&
          pip3 install matplotlib                                                &&
          pip3 install seaborn                                                   &&
          git clone https://github.com/tensorflow/quantum.git                    &&
          echo " "                                                               &&
          echo "Finished installing now running mnist Quantum"                   &&
          echo " "                                                               &&
          python3 a05train01.py                                                  &&
          echo "Mnist Quantum done!, by running:"                                &&
          echo "python3 a05train01.py"                                           &&
          echo "Try other ones if ready"                                                                                                                          

              
