image:
  file: .gitpod.Dockerfile
  
  
tasks:
  - init: pip install tensorflow                                                &&
          pip install tensorflowjs                                              &&
          pip install netron                                                    &&
          pip install tensorflow-quantum                                        &&
          pip install matplotlib                                                &&
          pip install seaborn                                                   &&
          python a01set01.py                                                       &&
          python a02data01.py                                                      &&
          python a03encode01.py                                                    &&
          python a04build01.py                                                     &&
          python a05predict01.py                                                     &&
          echo "Good luck"                                                                                                                          

              
