image:
  file: .gitpod.Dockerfile
  
  
tasks:
  - init: pip install tensorflow                                                &&
          pip install tensorflowjs                                              &&
          pip install netron                                                    &&
          pip install tensorflow-quantum                                        &&
          pip install matplotlib                                                &&
          pip install seaborn                                                   &&
          python a05train01.py                                                  &&
          git clone https://github.com/tensorflow/quantum.git                   &&
          echo "already ran python a05train01.py, try other ones"                                                                                                                          

              
