image:
  file: .gitpod.Dockerfile
  
  
tasks:
  - init: pip install tensorflow                                                &&
          pip install tensorflowjs                                              &&
          pip install netron                                                    &&
          pip install tensorflow-quantum                                        &&
          pip install matplotlib                                                &&
          pip install seaborn                                                   &&
          python a05train01.py                                                  &&
          echo "Good luck"                                                                                                                          

              
