image:
  file: .gitpod.Dockerfile
  
ports:
  - port: 6080
    onOpen: ignore 

  
tasks:
  - init:    pip3 install --upgrade pip                                             &&
             pip3 install tensorflow                                                &&
             pip3 install tensorflowjs                                              &&
             pip3 install netron                                                    &&
             pip3 install tensorflow-quantum                                        &&
             pip3 install matplotlib                                                &&
             git clone https://github.com/tensorflow/quantum.git                    &&
             pip3 install pennylane --upgrade                                       &&
             pip3 install pennylane-cirq autograd "tensorflow>=1.13.2"              &&
             pip3 install pytest-mock flaky  nlopt   dask[delayed]                  &&
             pip3 install  toml  scipy qulacs pillow  numpy                         &&
             pip3 install pennylane-sf pennylane-qiskit pennylane-cirq pytest-cov   &&
             pip3 install pennylane-forest pennylane-qsharp pytest pennylane-qchem  &&
             pip3 install torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html  &&
             pip3 install six==1.13.0 qsimcirq sympy==1.5.1 pyquil==2.21            &&
             pip3 install antlr4-python3-runtime==4.8 seaborn   pyyaml h5py         &&
             cd pennylaneai                                                         &&
             cd qml-demos                                                           &&
             cd alldata                                                             &&
             wget https://download.pytorch.org/tutorial/hymenoptera_data.zip        &&
             unzip  hymenoptera_data.zip                                            &&
             rm  hymenoptera_data.zip                                               &&
             cd ..                                                                  &&
             chmod a+x a01-show-errors.sh                                           &&   
             chmod a+x a02-set-antlr4-python3-runtime-to-4-7-2.sh                   &&   
             chmod a+x a03-increase-antlr4-python3-runtime.sh                       &&             
             echo " "                                                               &&
             echo "Running a program to prove it works"                             &&
             python3 tutorial_quantum_chemistry.py                                  &&
             ls -la                                                                 &&
             echo "Run the python files by typing python3 filename.py"
             
