image:
  file: .gitpod.Dockerfile
  
  
tasks:
  - init: pip install tensorflow                                                &&
          pip install tensorflowjs                                                 &&
          pip install netron                                                       &&
          pip install tensorflow-quantum                                        &&
          pip install matplotlib                                   &&
          node set01.py                                                            &&
          echo "Good luck"                                                                                                                          

              
