image:
  file: .gitpod.Dockerfile
  
ports:
  - port: 6080
    onOpen: ignore 
  
tasks:
  - command: pip3 install --upgrade pip                                             &&
             pip3 install tensorflow                                                &&
             pip3 install tensorflowjs                                              &&
             pip3 install netron                                                    &&
             pip3 install tensorflow-quantum                                        &&
             pip3 install matplotlib                                                &&
             pip3 install seaborn                                                   &&
             git clone https://github.com/tensorflow/quantum.git                    &&
             echo " "                                                               &&
             echo "Finished installing now running mnist Quantum"                   &&
             echo " "                                                               &&
             python3 a01-mnist-small.py                                             &&
             echo "Mnist Quantum done!, by running:"                                &&
             echo "python3 a01-mnist-small.py"                                      &&
             echo "Try other ones if ready"                                                                                                                          

              
